version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
