version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    groups:
      non-major-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
    groups:
      non-major-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-major-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
