source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib', '~> 2.0'

gem 'elixirize', '~> 0.5.0'

gem 'thin', '~> 1.7'

group :development do
  gem 'rake', '~> 12.1.0'
  gem 'rerun', '~> 0.11.0'
end

group :test do
  gem 'rack-test', '~> 0.7.0'
  gem 'rspec', '~> 3.6'
end
