services:
  website:
    image: brewfile-website:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_HOST=api
      - API_PORT=3000


  api:
    image: brewfile-api:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RACK_ENV=production
