# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |brewfiles| "https://github.com/#{brewfiles}" }

gem 'ougai', '~> 1.8'
gem 'puma', '~> 4.3.8'
gem 'rack-request-id', '~> 0.0.4'
gem 'rake', '~> 13.0'
gem 'roda', '~> 3.31'

group :development, :test do
  gem 'rb-fsevent', '~> 0.10.3'
  gem 'rerun', '~> 0.13.0'
end

group :development do
  gem 'rubocop', require: false
end

group :test do
  gem 'minitest', '~> 5.14'
end
