# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |brewfiles| "https://github.com/#{brewfiles}" }

gem 'puma', '~> 5.3'

gem 'ougai', '~> 2.0'
gem 'rack', '~> 2.2'
gem 'rack-app', '~> 7.7'
gem 'roda', '~> 3.62'

group :development, :test do
  gem 'rb-fsevent', '~> 0.10.3'
  gem 'rerun', '~> 0.13.0'
end

group :development do
  gem 'rubocop', '~> 1.18'
end

group :test do
  gem 'minitest', '~> 5.14'
end
