# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |brewfiles| "https://github.com/#{brewfiles}" }

gem 'puma', '~> 6.4'

gem 'ougai', '~> 2.0'
gem 'rack', '~> 3.0'
gem 'rack-app', '~> 8.0'
gem 'roda', '~> 3.62'

group :development, :test do
  gem 'rb-fsevent', '~> 0.11.2'
  gem 'rerun', '~> 0.13.0'
end

group :development do
  gem 'rubocop', '~> 1.62'
end

group :test do
  gem 'minitest', '~> 5.14'
end
