require "rake/testtask"

task default: :test

Rake::TestTask.new do |t|
  t.test_files = FileList['spec/**/*_spec.rb']
end

task :run do
  sh "rerun -- puma -p 4000 config.ru"
end

task :serve do
  sh "puma -p 4000 -b 'unix:///usr/local/api/shared/sockets/puma.sock' config.ru"
end
